name: Build Executables

# Auto-build for multiple platforms - Excel to SeaTable sync tool
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created, published]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output-name: excel-sea-sync-linux
            output-path: dist/excel-sea-sync-linux
          - os: windows-latest
            output-name: excel-sea-sync-windows.exe
            output-path: dist/excel-sea-sync-windows.exe
          - os: macos-latest
            output-name: excel-sea-sync-macos
            output-path: dist/excel-sea-sync-macos
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    # Windows特定：安装Visual C++ Redistributable
    - name: Install Visual C++ Redistributable (Windows)
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"
        Start-Process -Wait -FilePath "vc_redist.x64.exe" -ArgumentList "/quiet"
      shell: powershell
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==6.15.0
        
    # Windows特定构建
    - name: Build executable with PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: python build_windows_ci.py
      
    # Windows构建验证
    - name: Verify Windows build (Windows)
      if: runner.os == 'Windows'
      run: |
        dir dist
        if (Test-Path "dist/excel-sea-sync-windows.exe") {
          Write-Output "[OK] Windows executable found"
          $size = (Get-Item "dist/excel-sea-sync-windows.exe").Length
          Write-Output "File size: $size bytes"
        } else {
          Write-Output "[ERROR] Windows executable not found"
          exit 1
        }
      shell: powershell
        
    # 其他平台构建
    - name: Build executable with PyInstaller (Non-Windows)
      if: runner.os != 'Windows'
      run: |
        python build_standalone.py
        
    - name: Rename executable for release
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          # Windows构建已经生成正确的文件名，无需重命名
          if [ -f "dist/excel-sea-sync-windows.exe" ]; then
            echo "[OK] Windows executable found: dist/excel-sea-sync-windows.exe"
            ls -la dist/excel-sea-sync-windows.exe
          elif [ -f "dist/excel-sea-sync.exe" ]; then
            mv dist/excel-sea-sync.exe dist/${{ matrix.output-name }}
            echo "[OK] Renamed excel-sea-sync.exe to ${{ matrix.output-name }}"
          else
            echo "[ERROR] No Windows executable found"
            ls -la dist/
            exit 1
          fi
        else
          if [ -f "dist/excel-sea-sync" ]; then
            mv dist/excel-sea-sync dist/${{ matrix.output-name }}
            chmod +x dist/${{ matrix.output-name }}
            echo "[OK] Renamed and made executable: ${{ matrix.output-name }}"
          else
            echo "[ERROR] No executable found"
            ls -la dist/
            exit 1
          fi
        fi
      shell: bash
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output-name }}
        path: ${{ matrix.output-path }}
        retention-days: 90
        
    - name: Upload to release (if release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.output-path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}